# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: convert.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rconvert.proto\x12\x0e\x63onvert2vector\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\x0eVectorResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32\xab\x01\n\x0b\x43lipService\x12N\n\x0eGetImageVector\x12\x1c.convert2vector.ImageRequest\x1a\x1e.convert2vector.VectorResponse\x12L\n\rGetTextVector\x12\x1b.convert2vector.TextRequest\x1a\x1e.convert2vector.VectorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'convert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=33
  _globals['_IMAGEREQUEST']._serialized_end=62
  _globals['_TEXTREQUEST']._serialized_start=64
  _globals['_TEXTREQUEST']._serialized_end=91
  _globals['_VECTORRESPONSE']._serialized_start=93
  _globals['_VECTORRESPONSE']._serialized_end=125
  _globals['_CLIPSERVICE']._serialized_start=128
  _globals['_CLIPSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
